#!/usr/bin/env python3
"""Automated API schema documentation generator.

Introspects the dataclasses in src/pypinergy/models.py to generate
markdown reference tables for response fields.
"""

import ast
import os
import sys
from typing import Any, Dict, List


def generate_markdown(models_file_path: str) -> str:
    if not os.path.exists(models_file_path):
        raise FileNotFoundError(f"Models file not found: {models_file_path}")

    with open(models_file_path, "r", encoding="utf-8") as f:
        tree = ast.parse(f.read())

    classes: List[Dict[str, Any]] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue

        # Check if it's a dataclass (e.g. @dataclass, @dataclasses.dataclass, or called versions)
        is_dc = False
        for dec in node.decorator_list:
            # Matches @dataclass
            if isinstance(dec, ast.Name) and dec.id == "dataclass":
                is_dc = True
                break
            # Matches @dataclasses.dataclass
            elif (
                isinstance(dec, ast.Attribute)
                and isinstance(dec.value, ast.Name)
                and dec.value.id == "dataclasses"
                and dec.attr == "dataclass"
            ):
                is_dc = True
                break
            # Matches @dataclass(...)
            elif (
                isinstance(dec, ast.Call)
                and isinstance(dec.func, ast.Name)
                and dec.func.id == "dataclass"
            ):
                is_dc = True
                break
            # Matches @dataclasses.dataclass(...)
            elif (
                isinstance(dec, ast.Call)
                and isinstance(dec.func, ast.Attribute)
                and isinstance(dec.func.value, ast.Name)
                and dec.func.value.id == "dataclasses"
                and dec.func.attr == "dataclass"
            ):
                is_dc = True
                break

        if not is_dc:
            continue

        class_name = node.name
        class_doc = ast.get_docstring(node) or ""
        class_doc = " ".join(class_doc.strip().split())

        fields = []
        for i, stmt in enumerate(node.body):
            if isinstance(stmt, ast.AnnAssign):
                if not isinstance(stmt.target, ast.Name):
                    continue
                field_name = stmt.target.id
                field_type = ast.unparse(stmt.annotation)

                field_doc = ""
                if i + 1 < len(node.body):
                    next_stmt = node.body[i + 1]
                    if isinstance(next_stmt, ast.Expr):
                        if hasattr(ast, "Constant") and isinstance(next_stmt.value, ast.Constant):
                            val = next_stmt.value.value
                            if isinstance(val, str):
                                field_doc = val
                        elif isinstance(next_stmt.value, ast.Str):
                            field_doc = str(next_stmt.value.s)

                field_doc = " ".join(field_doc.strip().split())
                fields.append((field_name, field_type, field_doc))

        classes.append({"name": class_name, "docstring": class_doc, "fields": fields})

    if not classes:
        raise ValueError(f"No dataclasses detected in models file: {models_file_path}")

    # Sort classes by name for consistency
    classes.sort(key=lambda c: str(c["name"]))

    # Generate Markdown
    md = []
    md.append("# Pinergy API Models Schema")
    md.append("")
    md.append(
        "This document was automatically generated by running `python scripts/generate_schema_docs.py`."
    )
    md.append("It documents all API response dataclasses defined in `src/pypinergy/models.py`.")
    md.append("")
    md.append("## Table of Contents")
    for cls in classes:
        anchor = str(cls["name"]).lower()
        md.append(f"- [{cls['name']}](#{anchor})")
    md.append("")
    md.append("---")
    md.append("")

    for cls in classes:
        md.append(f"## {cls['name']}")
        if cls["docstring"]:
            md.append(cls["docstring"])
            md.append("")

        md.append("| Field Name | Type | Description |")
        md.append("| :--- | :--- | :--- |")
        if not cls["fields"]:
            md.append("| *No fields* | | |")
        else:
            for f_name, f_type, f_doc in cls["fields"]:
                # Escape pipe characters in type and description strings
                f_type_clean = f_type.replace("|", "\\|")
                f_doc_clean = f_doc.replace("|", "\\|")
                md.append(f"| `{f_name}` | `{f_type_clean}` | {f_doc_clean} |")
        md.append("")
        md.append("---")
        md.append("")

    return "\n".join(md)


def main() -> None:
    import argparse

    # Default path is relative to the directory containing this script file
    default_models_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "src", "pypinergy", "models.py")
    )

    parser = argparse.ArgumentParser(description="Generate API schema markdown documentation.")
    parser.add_argument(
        "--models-path",
        default=default_models_path,
        help=f"Path to models.py file (default: {default_models_path})",
    )
    parser.add_argument(
        "--output", help="Path to save the generated markdown (prints to stdout if not specified)"
    )
    args = parser.parse_args()

    try:
        markdown_content = generate_markdown(args.models_path)
    except (FileNotFoundError, ValueError) as err:
        print(f"Error: {err}", file=sys.stderr)
        sys.exit(1)

    if args.output:
        # Create output directories if they do not exist
        output_dir = os.path.dirname(os.path.abspath(args.output))
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)

        with open(args.output, "w", encoding="utf-8") as f:
            f.write(markdown_content)
        print(f"Successfully generated schema documentation at {args.output}")
    else:
        print(markdown_content)


if __name__ == "__main__":
    main()
